# Generated by Django 5.0.3 on 2024-03-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('imagen', models.ImageField(upload_to='porfolio_personal/media/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
