# Generated by Django 5.0.3 on 2024-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio_personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='imagen',
            field=models.ImageField(upload_to='porfolio/images/'),
        ),
    ]
