# Generated by Django 5.0.3 on 2024-03-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio_personal', '0003_redes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redes',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
