# Generated by Django 5.0.3 on 2024-03-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio_personal', '0004_alter_redes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
